# Generated by Django 4.2.3 on 2023-07-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_order_shippingaddress_review_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
