# Generated by Django 4.2.3 on 2023-07-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="/placeholder.png", null=True, upload_to=""
            ),
        ),
    ]
