# Generated by Django 4.2.3 on 2023-07-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_review_createdat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="paymentMethod",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="image",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="city",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="country",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="postalCode",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
